-- Left items (L to R)
require("items.apple")
require("items.menus")
-- require("items.menua")
-- require("items.workspaces")
require("items.spaces")
require("items.front_app")

-- Right items (R to L)
require("items.calendar")
require("items.widgets")
require("items.media")
