#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# Set the layout of the selected space
# bsp, stack or float
yabai -m config layout bsp
yabai -m config window_placement second_child

# padding set to 9px except top padding which is lowered to fit the bar
yabai -m config top_padding 7
yabai -m config bottom_padding 7
yabai -m config left_padding 7
yabai -m config right_padding 7
yabai -m config window_gap 7

# Create space on the active display
yabai -m space --create

# Delete focused space and focus first space on display
yabai -m space --destroy

# mouse settings
yabai -m config focus_follows_mouse autoraise

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# apps that yabai won't touch
yabai -m rule --add app="Reminders$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --ad app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|System Preferences|System Settings|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor)$" manage=off
