#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:40:0 \
  mouse_follows_focus on \
  focus_follows_mouse autoraise \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.7 \
  window_animation_duration 0.2 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance on \
  auto_padding on \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 8 \
  bottom_padding 7 \
  left_padding 7 \
  right_padding 7 \
  window_gap 8
#something

# apps that yabai won't touch
yabai -m rule --add app="Reminders$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --ad app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Ente Auth$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Facetime$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|Time Machine|System Settings|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor|Raycast)$" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
