require("items.widgets.control_center")
require("items.widgets.bluetooth")
-- require("items.widgets.caffeine")
require("items.widgets.volume")
require("items.widgets.battery")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.ram")
require("items.widgets.ssd")
-- require("items.widgets.trash")
