require("items.widgets.settings")
require("items.widgets.settings")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.battery")
-- require("items.widgets.ram")
-- require("items.widgets.yabai")
