#  ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
#  ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
#  ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
#  Smart session manager for the terminal
#  https://github.com/joshmedeski/sesh

# import = ["~/.config/sesh/configs/nu-sesh.toml"]
# blacklist = ["scratch"]

# default

[default_session]
startup_command = "nvim "
startup_command_ignore_dirs = ["~/repos", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

# common

[[session]]
name = "Notes"
path = "~/Notes-Vault"
startup_command = "nvim "

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "home ()"
path = "~"
startup_command = "ls"

# configs

[[session]]
name = "dotfiles"
path = "~/.dotfiles"

[[session]]
name = "wezterm config"
path = "~/.dotfiles/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "fish config"
path = "~/.dotfiles/fish"
preview_command = "bat --language=fish --style=snip --color=always ~/.dotfiles/fish/config.fish"

[[session]]
name = "kitty config"
path = "~/.dotfiles/kitty"
startup_command = "nvim kitty.conf"

[[session]]
name = "neovim config"
path = "~/.dotfiles/nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "tmux config"
path = "~/.dotfiles/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.dotfiles/tmux/tmux.conf"

[[session]]
name = "yazi config"
path = "~/.dotfiles/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "ghostty config"
path = "~/.dotfiles/ghostty"
startup_command = "nvim config"

[[session]]
name = "karabiner elements config"
path = "~/.dotfiles/karabiner"

[[session]]
name = "yabai config"
path = "~/.dotfiles/yabai"
startup_command = "nvim yabairc"
preview_command = "bat --style=snip --color=always ~/.dotfiles/yabai/yabairc"

[[session]]
name = "skhd config"
path = "~/.dotfiles/skhd"
startup_command = "nvim skhdrc"
preview_command = "bat --style=snip --color=always ~/.dotfiles/skhd/skhdrc"

# plugins

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
# startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"
startup_command = "nvim "
# TODO: add `--hide-tmux` to fzf command (or switch to sesh preview)
# startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none --hide-tmux) && exit"

[[session]]
name = "tmux plugins"
path = "~/.tmux/plugins"
# startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"
startup_command = "nvim "

# tools

# [[session]]
# name = "ollama"
# path = "~/.ollama"
# startup_command = 'grc tail -f ~/.ollama/logs/server.log'

# ideas / tasks

# TODO: experiment with long-living sesh picker (as session)
# [[session]]
# name = "sesh"
# path = "~/c/dotfiles/.config/sesh"
# startup_command = "sesh connect \"$(sesh list --icons | fzf)\""

# TODO: implement?
# [[session_preview]]
# pattern_folder_has = "README.md"
# preview_command = "glow -s light {}"

# TODO: potential feature ideas
# [[session]]
# name = "session"
# path = "~/path/to/session"
# startup_script = "~/git_repos/dotfiles/sesh/bin/spotify.sh"
# detached = true # never attach to this session, just create it in the background
# tmuxp = "~/.config/tmux/tmuxp/joshmedeski.com.yml"
# tmuxinator = "~/.config/tmux/tmuxinator/joshmedeski.com.yml"

# TODO: support wildcard paths
# [[session_wildcard]]
# session_path = "~/c/nu/main/packages/*"
# script_path = "~/.config/sesh/scripts/node_dev"

# notes

# NOTE: bat styles (--style)
# full, auto, plain, changes, header, header-filename,
